backend: &backend
  - 'src/**/*'
  - 'build.rs'

frontend: &frontend
  - 'ui/**/*'

# This should only contain additional things relevant to the build.
# You don't need to repeat things listed in backend or frontend.
build:
  - *backend
  - *frontend
  - 'prod_run.sh'
  - 'templates'
  - 'static/images/**/*'
  - 'data/**/*'
  - 'Cargo.toml'
  - 'Cargo.lock'
  - 'Dockerfile'
  - '.github/**/*'
