[package]
name = "team_heist_tactics"
version = "0.1.0"
authors = ["Daniel Porteous <danielporteous1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "*"
prost = "0.6"
# Only necessary if using Protobuf well-known types:
prost-types = "0.6"
rocket = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tera = "0.11"

[build-dependencies]
prost-build = { version = "0.6" }

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["tera_templates"]
