export const WEBSOCKET_ACTION_PREFIX = "REDUX_WEBSOCKET";
export const WEBSOCKET_ACTION_PREFIX_FULL = "REDUX_WEBSOCKET::";

export const CANVAS_WIDTH = 1600;
export const CANVAS_HEIGHT = 1000;
export const SERVER_WIDTH = 500;
export const SERVER_HEIGHT = 500;
