name: Build container

on:
  push:
    branches: [ master ]

jobs:
  build_everything:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        image_name: team_heist_tactics
