name: Frontend style check

defaults:
  run:
    working-directory: ui

on:
  pull_request:
    branches: [ master ]

jobs:
  frontend_style:
    name: yarn run style-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.4.0'
      - run: yarn install
      - run: yarn run style-check
