name: Frontend style check

on:
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Run yarn run tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.4.0'
      - run: yarn install
      - run: yarn run style-check
