name: Frontend tests

defaults:
  run:
    working-directory: ui

on:
  pull_request:
    branches: [ master ]

jobs:
  frontend_tests:
    name: yarn run tsc / test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.4.0'
      - uses: arduino/setup-protoc@master
        with:
          version: '3.12.3'
      - run: yarn install
      - run: cp ../src/types.proto .
      - run: ./generate_types.sh
      - run: yarn run tsc
      - run: yarn run test
